services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`sfvn.vfoodie.top`)"
            - "traefik.http.routers.nginx.entrypoints=web"
            - "traefik.http.routers.nginx.entrypoints=websecure"
            - "traefik.http.routers.nginx.tls.certresolver=myresolver"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
    ####################################################################################################
    # Traefik
    ####################################################################################################
    traefik:
        image: traefik:v2.8
        command:
            - "--api.insecure=true" # Bật API cho dashboard
            - "--api.dashboard=true" # Bật dashboard
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
            - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
            - "--entrypoints.traefik.address=:8081"
        ports:
            - "81:81"
            - "443:443"
            - "8081:8081" # Traefik dashboard
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./traefik/letsencrypt:/letsencrypt"

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        image: mysql:8.1
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: strong
            MYSQL_USER: strong
            MYSQL_PASSWORD: strong

    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - .docker/phpmyadmin/sessions:/sessions

    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        image: adminer
        ports:
            - 9090:8080
        depends_on:
            - db

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
            - 1025:1025

    ####################################################################################################
    # Redis
    ####################################################################################################
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - .docker/redis/data:/data
        ports:
            - 6379:6379
    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass

    ####################################################################################################
    # PostgreSQL
    ####################################################################################################
    # db:
    #     image: postgres:16
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - .docker/db/data:/var/lib/postgresql/data
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         - POSTGRES_USER=refactorian
    #         - POSTGRES_PASSWORD=refactorian
    #         - POSTGRES_DB=refactorian

    ####################################################################################################
    # pgAdmin
    ####################################################################################################
    # pgadmin:
    #     image: dpage/pgadmin4
    #     ports:
    #         - 5050:80
    #     environment:
    #         - PGADMIN_DEFAULT_EMAIL=admin@admin.com
    #         - PGADMIN_DEFAULT_PASSWORD=password
    #     depends_on:
    #         - db
